# Syllabus {-}

**Course:** ENST/MRNE 395 Coastal Monitoring Fall 2024  
**Class time and location:** Fridays 1:10 - 4:20 Schaefer Hall  
**Instructor:** Dr. Cassie Gurbisz  (you're welcome to call me Cassie)  
**Email:** cbgurbisz@smcm.edu  
**Office hours:** Tuesdays 12:00-2:00 Kent Hall 308  
**Website:** https://smr-monitoring.github.io/MRNE395-2024FA/

### Course description {-}
Students will learn how to conduct ecological monitoring on the St. Mary’s River, a tidal tributary of Chesapeake Bay. We will use a variety of sampling methods to measure chemical concentrations, animal abundances, and metabolic rates in the estuarine environment. We'll also use quality assurance/quality control measures to clean the data we collect before publishing it to our publicly available data dashboard. This 2-credit course meets once per week and also requires students to work in groups outside of class meetings to collect and process samples. Students should be prepared to work outdoors in inclement weather.

### Course materials {-}
All of the readings and software in this class are either free or will be provided by the instructor.

### Working outside {-}
This course involves a lot of outdoor work. Sometimes the weather will be beautiful, but more often it will be hot, sunny, buggy, cold, wet, windy, or a combination of these uncomfortable conditions. We will go out rain or shine unless the conditions are unsafe. It is important that you come to class prepared with whatever you need to keep yourself safe and comfortable outside. It's always a good idea to have a hat and sunscreen and a waterproof layer, even if rain is not in the forecast. For boat work, it is almost always much cooler on the water than land, especially in the spring, fall, and winter, so come prepared with multiple layers. Closed-toe shoes are required on the boat. Crocs or sneakers are fine in warm weather. Rubber boots are ideal in cooler weather but sneakers or anything with a grippy rubber sole are fine too. Do not wear flip-flops, heels, or nice shoes that can't get wet or that could scuff up the boat deck. 

I recommend investing in good rain gear, including a jacket, bibs, and boots, especially if you plan to continue doing fieldwork on the water beyond this class. These items are very nice to have, even if it's not raining, because sampling can be wet and messy. [Grundens](https://grundens.com/) is a reputable marine work gear supplier and they have some affordable options. [Outdoor Research](https://www.outdoorresearch.com/) also sells high-quality gear and you can apply for a [student discount](https://www.outdoorresearch.com/pages/vip-program?gad_source=1&gclid=Cj0KCQjwkdO0BhDxARIsANkNcrfTTRmTvBF6i9f4siwcZSvr-3FYPgDXYPUw5zkBXpXfyFCTJc8cJKAaAtSCEALw_wcB). 

### Learning outcomes {-}
At the completion of this course, students will have an in-depth understanding of why and how we conduct ecological monitoring in coastal systems.

Specific outcomes include being able to:

* describe the ecological and policy context of coastal monitoring
* describe coastal monitoring methods and procedures
* conduct coastal monitoring independently and with a team using correct and appropriate methods and procedures

### Grading and assessment {-}
This course uses a variation of "specifications grading," where we rely less on evaluating every assignment with a letter or number and instead focus on making sure we're generally making good progress in our learning. [Research has shown](https://www.alfiekohn.org/article/case-grades/) that grading doesn't improve learning and can sometimes even harm learning. Rather than submitting work "in exchange" for a letter or number grade, most assignments will be evaluated based on whether or not they meet the "specifications," or "specs" of that particular assignment. If the specs are not met, you'll often have the opportunity to revise your assignment until the specs are met so that you have more than one chance to demonstrate your learning. Your final grade will be based on the number of assignments for which you meet the specs and, therefore, demonstrate your mastery of the course topics. With this approach to evaluation, the goal is to emphasize truly becoming an expert in the course content. 

The following outlines how grades are earned:

* **A:** Meet specs on at least xx quizzes/homeworks; earn at least 90% on final exam
* **B:** Meet specs on at least xx quizzes/homeworks; earn at least 80% on final exam
* **C:** Meet specs on at least xx quizzes/homeworks; earn at least 70% on final exam
* **D:** Meet specs on at least xx quizzes/homeworks; earn at least 70% on final exam; 3 or more unexplained absences* 
* **F:** Meet specs on less than xx quizzes/homeworks; earn less than a 70% on final exam; 3 or more unexplained absences*

*Unexplained absence:* Missing class without notifying the professor (in other words, “ghosting” the class). As long as you let the instructor know you won’t be able to make it to class, an absence is considered “explained,” no doctor’s note or other official documentation needed. Please don’t come to class if you are sick! Just be sure to keep me in the loop via a quick email.

On the flip side, please consider the consequences of missing class meetings – this is a very hands-on course where most of the learning takes place in person. It will be hard to learn and, therefore, pass the class if you’re not here to participate. This is why attendance is included in the specs for earning a D or F in the class: since we only meet once a week, missing 3 class sessions is equal to missing three weeks of class. If we are not in close communication about your absences, catching up on this much missed work will be difficult if not impossible. IMHO, this course is fun and interesting with many practical applications for your future career in marine science and adjacent fields, so hopefully this won’t be an issue because you’ll be excited to come to class!

**Homework assignments and quizzes**

Formative assessments will generally take the form of written and practical quizzes and homework assignments. They are designed to 1) help the instructor monitor how well you’re learning and 2) help you monitor your own learning and make adjustments to improve. These assignments can be revised during class based on discussion with your peers and instructor so that you can identify and correct any misconceptions your may have and consider how you might improve your study habits. Learning outcomes for each week will be provided and each quiz/homework assignment will clearly assess those outcomes. Since the final exam will be assessing the same learning outcomes, these assignments will also serve as great study material for the exams.

Quizzes and homework assignments are evaluated on a “meets specs/does not meet specs” basis to avoid stressing over every point earned and lost. To meet specs on a quiz or homework assignment (unless otherwise noted), your work should be at least 50% correct before revision and at least 85% correct after revision with an honest reflection on any revisions made. Quizzes can be made up during the instructor’s office hours but revisions are not possible on make-up quizzes since they are based on in-class peer collaboration. Missed quizzes must be made up within two weeks of the day you missed the quiz.

**Final exam**

Summative assessments evaluate your learning and proficiency at the end of the course. The summative assessment in this course will take the form of a cumulative exam that has both a written and practical component. The written portion will assess your understanding of the ecological and policy context of coastal monitoring and your grasp of proper monitoring methods. For the practical component, we’ll schedule individual meetings in which you demonstrate your ability to properly calibrate instruments, collect samples, etc. Standard operating procedures (SOPs) will be provided for the practical exam but tasks must be completed within the time provided. Students can use one page of hand-written notes for the written exam portion. The final exam cannot be revised but the course structure and policies are intentionally designed to help you learn a lot (and therefore do well on the exams) as long as you show up and do the work! If you need to miss the final exam, please contact the instructor to reschedule it.

**Extra credit**

The specs grading system is designed to reduce anxiety over grades, but I recognize that you still may experience some stress over the exam and quizzes, especially if your exam grade is just below the benchmark for a particular course grade or you did not meet specs on one too many quizzes to earn the grade you want. I will offer multiple opportunities that will enable you to earn up to three extra credit points, which you can add to your final exam grade or use as a "free pass" to automatically meet specs on a quiz. So if, for example, you earn a 78% on the exam, your three extra credit points can increase the grade to an 81% and you can, therefore earn a B in the class. Or if you only meet the specs on xx quizzes but you needed to pass xx to earn a B, you can use one of your extra credit points to automatically pass your missing quiz. Several extra credit opportunities are already listed on the class website and more will be added and announced throughout the semester.

### More policies {-}

**Attendance and late work**

If you need to miss class, first make sure to communicate this with me. Then check the class [schedule](https://enst222.github.io/website/schedule.html) to see what you missed, review relevant slides and readings, and complete missed assignments on your own. If you missed a quiz, contact me to reschedule it. Missed quizzes must be made up within 2 weeks. 

I am similarly flexible about late work. If you need an extra day or two to complete an assignment, just ask - it's usually not a problem. However, you should think about the purpose of a particular due date and how a late submission will affect your learning. In the case of projects, a late submission might mean you will miss the opportunity to get feedback on your work. For assignments and data challenges, you might miss the chance to work collaboratively with your peers to solve stubborn data or coding challenges. You should take these learning opportunities into consideration before requesting an extension.

**Engaged learning**

SMCM has recently decreased the amount of time allocated to class meetings. Because our course meeting times are longer than required for a 2-credit course, most of our "engaged learning" will take place via hands-on activities in class. Occasionally, students will also make some monitoring measurements on their own outside of class. 

**Office hours**

Office hours are set times dedicated to students. This means that I will be in my office waiting for you to come by talk to me during that time. 

### SMCM resources {-}

**Accommodations and Accessibility:** SMCM is committed to providing access to the learning and living experience to students with disabilities and disabling health conditions. If you have received a letter from the Office of Accessibility Services (OAS), which outlines the academic accommodations to which you are entitled to and you want  those accommodations to apply to this course, you MUST share your letter and meet with me to review that letter. If you suspect that you have a learning or living need related to a disability or disabling health condition that could benefit from  accommodations, you should contact the Office of Accessibility Services, who can help you learn more about how to proceed. Email: adasupport@smcm.edu

**The Wellness Center:** If you find yourself struggling with your mental or physical health this semester, please let me know.  I am one of many people here at SMCM who care about you and your welfare. The Wellness Center (240-895-4289) provides numerous confidential health and counseling services including same day/next day connections to counseling by calling 240-895-4289 or emailing the Director at jljolly@smcm.edu. To learn more about Wellness Center Services please go to their webpage at https://www.smcm.edu/wellness/

**Office of Student Support Services:** The Office of Student Success Services (OS3) provides free tutoring services and academic coaching with professional staff and Peer Academic Success Strategies (PASS) Specialists. You may drop into the PASS office in 230 Glendening for walk-in appointments on Mondays 11:30-1:00 and Tuesdays 4:30 to 6:00. You can also email PASS@smcm.edu. For tutoring for a specific course, please email your request to tutoring@smcm.edu. For any other help call 240-895-4388 or email os3@smcm.edu.

**The Writing and Speaking Center:** Located on the first floor of the main Library, the Writing & Speaking Center offers free peer tutoring in writing and speaking. The peer tutors are students themselves, but they have completed extensive hands-on training to learn how to assist their peers at any step of the process (planning, drafting, or revising) for any writing or speaking assignment. The peer tutors will not make decisions about revision for you and will instead work collaboratively with you to discuss ideas and consider options so that you can choose how best to revise on your own. This collaborative approach is one of the best ways to help students develop their abilities because all writers and speakers need audiences—just ask the peer tutors, who often schedule tutorials with each other. To make an appointment, please visit www.smcm.edu/writingcenter and click the “Schedule an Appointment” button. If you have questions or need assistance, please contact Director Ben Click at baclick@smcm.edu.

**Office of Title IX Compliance and Training:** St. Mary's College of Maryland is committed to helping create a safe and open learning environment for all students. If you (or someone you know) have experienced any form of sexual misconduct, including sexual assault, dating or domestic violence, or stalking, know that help and support are available.
 
The College strongly encourages all community members to take action, seek support, and report incidents of sexual misconduct to the Title IX Office.  Under Title IX of the Education Amendments of 1972, I am required to disclose information about such misconduct to the Title IX Office.
If you would like to talk to a confidential employee who does not have this reporting responsibility, you can contact SMCM Wellness Center or Health Services at (240) 895-4289. 
 
For more information about reporting options and resources at St. Mary's College of Maryland and the community, please visit the Office of Title IX Compliance and Training.
