# Reflections {-}

Our assessment system in this class is "ungrading." As [The Case Against Grades](https://www.alfiekohn.org/article/case-grades/) shows, grading doesn't improve learning and can sometimes even harm learning. Rather than submitting work to me for feedback in exchange for a letter or number grade, your peers and I will provide qualitative feedback. You'll decide whether and how the work should be revised so that your work best reflects your own learning progress. This system is designed to spark your inner motivation to do your best work. Periodically, you'll reflect on your learning process and the products of your work and give yourself a letter grade, since we still need to submit grades to the registrar at the end of the semester.

## Mid-semester learning reflection {-}

Recall that by the completion of this course, students should be able to gain insight from environmental data **reproducibly** (with literate programming and version control) and **collaboratively** using **modern programming tools and techniques**. 

Specific outcomes include being able to:

* visualize data using `ggplot2`
* wrangle and tidy data tables using `dplyr` functions to generate a suitable data set for analysis
* use functions and iterative programming to automate analysis tasks
* define research questions and hypotheses
* construct statistical models to quantify patterns and make predictions
* interpret data in the context of prior knowledge in the environmental or marine science domains 
* communicate results and document code using RMarkdown documents 
* store data and code using a clean and clear system of organization
* use version control tools (Git and GitHub) to collaborate and share code

Please discuss your growth so far with respect to these objectives. Talk about what, specifically, you have learned in the course. What exactly have you done that has helped you learn? What can you change about your work habits and processes to get the most out of the course? Comment on the quality of your work and contributions to the class learning community so far. Are you putting your best effort into participating in class and lab activities? Is your work polished and professional? Finally, if you had to give yourself a letter grade at this point, what would it be and why?

Your reflection should be detailed and thoughtful - you should aim for at least ~300 words. Please write a cohesive narrative rather than a list of responses to the prompts.

<i class="fa fa-chevron-circle-right"></i> Please submit your reflection using the [mid-semester learning reflection form](https://forms.gle/ERr3ni7w7Jb61oFu5)

## Final learning reflection {-}

The assignment is the same as above, but you should reflect on your cumulative learning throughout the entire semester.

<i class="fa fa-chevron-circle-right"></i> Please submit your reflection using the [final learning reflection form](https://forms.gle/obRy1Z3Q7aRe3tWs5)
