# Extra credit {-}

The following is a list of extra credit opportunities for Fall 2024. The date, accompanying assignment, points earned, and other information is included. 

Most opportunities include a reflection component. Your reflection should be ~300-500 words. It should first briefly summarize the event/experience, then draw linkages between the event/experience and this course, other MRNE/ENST courses, and/or your professional goals. You might also discuss how the event/experience changed the way you think about a particular topic, what new questions it evoked for you, or whatever else you think is relevant. In general, reflections should be well-written, gramatically correct, and thoughtful. Don't use ChatGPT to write your reflection - at this point, LLMs can generate coherent text, but the output often lacks depth, interest, and creativity. Your reflection should be in-depth, interesting, and creative - only your brain can write like that (at least for now...)! If your reflection does not meet these criteria, I will ask that you revise and resubmit it until it does.  

* CBL Distinguished Scholar Seminars usually Wednesdays 3:30 Chesapeake Biological Laboratory Solomon's MD
